language: groovy
before_install:
- cd api
- jdk_switcher use oraclejdk8
- rm -rf ~/.nvm && git clone --depth=1 https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 8
script:
- cd ../frontend && npm install && npm test -- --coverage && npm run pactPublish
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
