version: '2'
services:
  neo4j:
    image: "neo4j:3.1"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./.neo4j/data:/data"
    environment:
      NEO4J_AUTH: "none"
  api:
    build: api
    depends_on:
      - neo4j
    ports:
      - "8080:8080"
    environment:
      NEO4J_HOST: "http://neo4j:neo4j@neo4j:7474"
    links:
      - neo4j
    volumes:
      - "./.gradle_cache:/root/.gradle:rw"
  frontend:
    build: frontend
    environment:
      API_ENDPOINT: "http://localhost:8080/"
    ports:
      - "80:80"
    links:
      - api

