
neo4j-db:
  image: neo4j:3.0
  container_name: neo4j-db
  ports:
    - "7474:7474"
    - "7687:7687"
  volumes:
    - ./.neo4j/data:/data
  environment:
    # Turn off auth for neo4j for now due to: https://github.com/neo4j/docker-neo4j/issues/32
    NEO4J_AUTH: none

#mysql-db:
#  image: mysql
#  container_name: mysql-db
#  ports:
#    - "3306:3306"
#  environment:
#    MYSQL_ROOT_PASSWORD: my-secret-pw
#    MYSQL_DATABASE: berry-street

berry-api:
  build: ./api
  container_name: berry-api
  links:
    #- mysql-db
    - neo4j-db
  ports:
    - "8080:8080"
  environment:
    # MYSQL_HOST: mysql-db
    # MYSQL_USER: root
    # MYSQL_PASSWORD: my-secret-pw
    NEO4J_HOST: http://neo4j:neo4j@rhok.berrystreet.org.au:7474
    # NEO4J_USER: neo4j
    # NEO4J_PASSWORD: my-secret-pw

berry-frontend:
  build: ./frontend
  container_name: berry-frontend
  links:
    - berry-api
  ports:
    - "80:80"
  environment:
    API_ENDPOINT: http://berry-api:8080/
