import React, { Component } from 'react';

export class LandingPanel extends Component {
    constructor(props) {
        super(props)
    }
    render() {
        return <div className="container-fluid">
            <h1>Case View</h1>
            <hr />
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Lorem sed risus ultricies tristique nulla aliquet. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Interdum consectetur libero id faucibus nisl tincidunt eget. Lectus sit amet est placerat in. Non enim praesent elementum facilisis leo vel. Volutpat ac tincidunt vitae semper. Blandit aliquam etiam erat velit. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Justo eget magna fermentum iaculis eu non diam phasellus vestibulum.</p>
            <p>Tincidunt dui ut ornare lectus sit. Vestibulum mattis ullamcorper velit sed ullamcorper. Ultrices mi tempus imperdiet nulla malesuada. Purus sit amet luctus venenatis lectus magna. Nunc sed blandit libero volutpat sed cras. Arcu cursus euismod quis viverra nibh cras pulvinar. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Scelerisque eu ultrices vitae auctor eu. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Interdum velit euismod in pellentesque massa. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. A diam maecenas sed enim ut sem viverra aliquet eget. Gravida cum sociis natoque penatibus et magnis. Eu lobortis elementum nibh tellus. Nisl nunc mi ipsum faucibus vitae. Ac feugiat sed lectus vestibulum. Et tortor at risus viverra adipiscing at in tellus. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero id. Sem fringilla ut morbi tincidunt augue interdum. Duis at tellus at urna condimentum mattis pellentesque id nibh.</p>
            <p>Mattis aliquam faucibus purus in. Quam viverra orci sagittis eu volutpat odio facilisis. Lacus luctus accumsan tortor posuere. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Est sit amet facilisis magna etiam tempor orci eu. Mauris a diam maecenas sed enim ut sem viverra. Quisque egestas diam in arcu. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Ultricies leo integer malesuada nunc vel risus commodo. Arcu vitae elementum curabitur vitae. Arcu ac tortor dignissim convallis aenean et tortor. Justo donec enim diam vulputate ut pharetra sit amet. Neque volutpat ac tincidunt vitae semper. Nulla malesuada pellentesque elit eget gravida cum. Vulputate enim nulla aliquet porttitor lacus luctus. Nam libero justo laoreet sit amet cursus sit amet dictum. Malesuada proin libero nunc consequat interdum varius. Eget nunc lobortis mattis aliquam faucibus. Mi sit amet mauris commodo quis imperdiet. Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.</p>
            <p>Aliquam ultrices sagittis orci a scelerisque purus semper. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Tortor consequat id porta nibh venenatis cras sed felis. Ultrices sagittis orci a scelerisque purus semper eget duis. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Etiam tempor orci eu lobortis elementum. Nam at lectus urna duis convallis convallis tellus id. Semper auctor neque vitae tempus quam pellentesque nec. Aenean sed adipiscing diam donec adipiscing tristique. Enim nunc faucibus a pellentesque sit amet porttitor.</p> 
            <p>Eget arcu dictum varius duis at. A lacus vestibulum sed arcu non odio. Morbi tempus iaculis urna id. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Leo a diam sollicitudin tempor id eu nisl nunc. At erat pellentesque adipiscing commodo. Euismod nisi porta lorem mollis aliquam. Orci a scelerisque purus semper eget duis. Non arcu risus quis varius quam quisque id diam vel. Lacus laoreet non curabitur gravida arcu ac tortor. Enim sed faucibus turpis in eu mi bibendum neque egestas. Venenatis cras sed felis eget velit aliquet sagittis. At risus viverra adipiscing at in. Lacus vel facilisis volutpat est velit egestas dui id ornare.</p>
        </div>;
    }
}